# Generated by Django 5.2 on 2025-04-18 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timezone", models.CharField(max_length=150)),
                ("currency", models.CharField(max_length=150)),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "additionalinfo",
            },
        ),
        migrations.CreateModel(
            name="customer",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "CUSTOMER_ID",
                    models.CharField(
                        db_column="CUSTOMER_ID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "EMAIL",
                    models.EmailField(
                        db_column="USER_NAME", max_length=100, unique=True
                    ),
                ),
                ("First_Name", models.CharField(db_column="FIRST_NAME", max_length=50)),
                ("Last_Name", models.CharField(db_column="LAST_NAME", max_length=50)),
                ("is_staff", models.CharField(default="N", max_length=1)),
                ("is_superuser", models.CharField(default="N", max_length=1)),
                ("is_verified", models.CharField(default="N", max_length=1)),
                ("is_active", models.CharField(default="Y", max_length=1)),
                (
                    "CREATE_DATE",
                    models.DateTimeField(auto_now_add=True, db_column="CREATE_DATE"),
                ),
                (
                    "CREATED_BY",
                    models.CharField(db_column="CREATED_BY", max_length=100),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, db_column="LAST_LOGIN"),
                ),
                (
                    "Last_Updated_Date",
                    models.DateTimeField(auto_now=True, db_column="LAST_UPDATED_DATE"),
                ),
                (
                    "Last_Updated_By",
                    models.CharField(db_column="LAST_UPDATED_BY", max_length=100),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        db_column="AUTH_PROVIDER", default="email", max_length=100
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customer_set",
                        related_query_name="customer",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customer_set",
                        related_query_name="customer",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "CUSTOMER",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("profile_photo", models.BinaryField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "UserProfile",
            },
        ),
    ]
