# Generated by Django 5.2 on 2025-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="CUSTOMER_ID",
            field=models.IntegerField(
                db_column="CUSTOMER_ID", primary_key=True, serialize=False
            ),
        ),
    ]
