# Generated by Django 5.2 on 2025-04-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_setting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSetting",
            fields=[
                ("trade_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_id", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("from_field", models.CharField(db_column="from_value", max_length=50)),
                ("to_field", models.CharField(db_column="to_value", max_length=50)),
                (
                    "customer_id",
                    models.ForeignKey(
                        db_column="customer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_login_trade_setting",
            },
        ),
    ]
