# Generated by Django 5.2 on 2025-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioOrganizer",
            fields=[
                (
                    "ACCOUNT_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=255)),
                ("ACCOUNT_NAME", models.CharField(max_length=100, unique=True)),
                ("STOCK_TYPE", models.CharField(max_length=100)),
                (
                    "INITIAL_DEPOSIT",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("IS_ACTIVE", models.CharField(max_length=1)),
                ("CREATE_DATE", models.DateField()),
                ("CREATED_BY", models.CharField(max_length=100)),
                ("LAST_UPDATED_DATE", models.DateField()),
                ("LAST_UPDATED_BY", models.CharField(max_length=100)),
                ("PROFIT_CALCULATION_METHOD", models.CharField(max_length=100)),
                ("BALANCE_DATE", models.DateTimeField()),
                ("BALANCE_TIME", models.TimeField()),
                ("BALANCE_DESCRIPTION", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "PORTFOLIO_ORGANIZER",
            },
        ),
    ]
