# Generated by Django 5.2 on 2025-04-13 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "COMMISSION_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=10)),
                ("ACCOUNT_ID", models.CharField(max_length=10)),
                ("TRANSACTION_DETAIL_ID", models.CharField(max_length=10)),
                ("FEE", models.CharField(max_length=10)),
                ("COMMISSION", models.CharField(max_length=10)),
                ("IS_ACTIVE", models.CharField(max_length=1)),
                ("CREATE_DATE", models.DateField(default=django.utils.timezone.now)),
                ("CREATED_BY", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "COMMISSION",
            },
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "TRANSACTION_DETAIL_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=10)),
                ("ACCOUNT_ID", models.CharField(max_length=10)),
                ("TRANSACTION_DATE", models.DateTimeField()),
                ("TYPE", models.CharField(max_length=1)),
                ("TICKER", models.CharField(max_length=10)),
                ("IDENTIFIER", models.CharField(max_length=50)),
                ("QUANTITY", models.FloatField()),
                ("ORDER_TYPE", models.CharField(max_length=10)),
                ("PRICE", models.CharField(max_length=10)),
                ("IS_ACTIVE", models.CharField(max_length=1)),
                ("CREATE_DATE", models.DateField()),
                ("CREATED_BY", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "TRANSACTION_DETAIL",
            },
        ),
        migrations.CreateModel(
            name="TransactionMapping",
            fields=[
                (
                    "TRANSACTION_MAPPING_ID",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=10)),
                ("ACCOUNT_ID", models.CharField(max_length=10)),
                ("TRANSACTION_SUMMARY_ID", models.CharField(max_length=10)),
                ("TRANSACTION_DETAIL_ID", models.CharField(max_length=10)),
                ("IS_ACTIVE", models.CharField(max_length=1)),
                ("CREATE_DATE", models.DateField()),
                ("CREATED_BY", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "TRANSACTION_MAPPING",
            },
        ),
        migrations.CreateModel(
            name="TransactionSummary",
            fields=[
                (
                    "TRANSACTION_SUMMARY_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=10)),
                ("ACCOUNT_ID", models.CharField(max_length=10)),
                ("TRANSACTION_DATE", models.DateField()),
                ("TYPE", models.CharField(max_length=10)),
                ("TICKER", models.CharField(max_length=10)),
                ("IDENTIFIER", models.CharField(max_length=50)),
                ("QUANTITY", models.FloatField()),
                ("AVG_BUY_PRICE", models.CharField(max_length=50)),
                (
                    "AVG_SELL_PRICE",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("COMMISSION", models.CharField(blank=True, max_length=15, null=True)),
                ("FEES", models.CharField(blank=True, max_length=15, null=True)),
                ("PROFIT_LOSS", models.CharField(max_length=50)),
                ("TRADE_START_TIME", models.DateField()),
                ("TRADE_END_TIME", models.DateField(blank=True, null=True)),
                (
                    "TRADE_DURATION",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("IS_ACTIVE", models.CharField(max_length=1)),
                ("CREATE_DATE", models.DateField()),
                ("CREATED_BY", models.CharField(max_length=100)),
                ("IS_PROCESSED", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "TRANSACTION_SUMMARY",
            },
        ),
    ]
