# Generated by Django 5.2 on 2025-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_file", "0003_alter_transactiondetail_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondetail",
            name="TYPE",
            field=models.CharField(max_length=10),
        ),
    ]
