# Generated by Django 5.2 on 2025-04-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_file", "0005_tradelogs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TradeLogs",
        ),
    ]
