# Generated by Django 5.2 on 2025-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_file", "0006_delete_tradelogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="FILENAME",
            field=models.CharField(default="unknown_file.csv", max_length=100),
        ),
    ]
