# Generated by Django 5.2 on 2025-04-15 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradeLogs",
            fields=[
                (
                    "TRADE_LOG_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CUSTOMER_ID", models.CharField(max_length=10)),
                ("ACCOUNT_ID", models.CharField(max_length=10)),
                ("FILE_NAME", models.CharField(max_length=255)),
                (
                    "UPLOAD_TIME",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("TOTAL_ENTRIES", models.IntegerField()),
                ("DUPLICATE_ENTRIES", models.IntegerField()),
                ("CREATE_DATE", models.DateField(default=django.utils.timezone.now)),
                ("CREATED_BY", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "TRADE_LOGS",
            },
        ),
    ]
